skillMetadata:
  sections:
    - name: Cache Settings
      fields:
        - name: allow_update
          type: checkbox
          label: Allow update of scripts via intent (disable to prevent requests to update scripts)
          value: "true"
        - name: auto_update
          type: checkbox
          label: Automatically update scripts from remote server
          value: "true"
